### PR TITLE
fix(core): :bug: hot reload of directories

### LINKED ISSUE #387: Hot Reload & Updating options knob does not work
**Description**
I tried to use widgetbook and created a small sample for myself. However, when using an options knob on a button with "button style", I need to switch panes to reflect the change in the button.

The second problem is hotreloading (in desktop environment), which does not update anything when I tell android studio to hot reload. Only a full hot restart does reflect the latest changes (even with a `UniqueKey()` in the whole widgetbook app).

**Steps To Reproduce**

1. Start widgetbook
2. Change some title in the code
3. use hotreload -> nothing happens

1. Use widgetbook
2. Use an options knob
3. Change it in the widget you are displaying -> widget is not rerendered

**Expected Behavior**
Both features should work like expected.

**Screenshots**
Hot Reload

Knob

**Additional Context**

<details>
  <summary>Widgetbook build function</summary>
  
```dart
  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      key: UniqueKey(),
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      devices: [
        Samsung.s10,
        Apple.iPhone12ProMax,
        Apple.iPhone13Mini,
        Apple.iPhone11ProMax,
        Apple.iPhone11,
        Desktop.desktop1080p,
        Desktop.desktop1440p,
      ],
      themes: [
        WidgetbookTheme(
          name: 'Default',
          data: ThemeData(
              colorScheme: const ColorScheme.light(primary: AppColors.signal500, secondary: AppColors.text500)),
        )
      ],
      categories: [
        WidgetbookCategory(name: 'Brand', widgets: [
          WidgetbookComponent(name: 'Default', isExpanded: true, useCases: [
            ...colorUseCases,
            ...iconographyUseCases,
            ...typographyUseCases,
          ])
        ]),
        WidgetbookCategory(name: 'Components', isExpanded: true, widgets: [
          buttonsComponent,
        ]),
      ],
      appInfo: AppInfo(name: 'Widgetbook'),
    );
  }
```
  
</details>

<details>
  <summary>buttons component</summary>

```dart
WidgetbookComponent buttonsComponent = WidgetbookComponent(name: 'Button', useCases: [
  WidgetbookUseCase(
    name: 'Default',
    builder: (context) => Center(
        child: Button(
            text: context.knobs.text(label: 'Text', description: 'Button label', initialValue: 'Click Me'),
            style: context.knobs.options(label: 'Style', options: [
              const Option(label: 'Primary', value: ButtonStyle.primary),
              const Option(label: 'Secondary', value: ButtonStyle.secondary),
            ]),
            onPressed: () {})),
  ),
  WidgetbookUseCase(
    name: 'Icon Button',
    builder: (context) => Center(
        child: IconButton(
            key: UniqueKey(), onPressed: () {}, icon: const Icon(AppIcons.back, color: AppColors.signal500))),
  ),
]);
```
</details>

### PR DESCRIPTION
**Pull request by jenshor**
Fixes hot reloading of `directories` and applies the existing `searchQuery` to the new `directories`

### List of issues which are fixed by the PR
- fixes #387
- the other problem of #387 already has a test and works

### CODE REVIEW

File: packages/widgetbook_core/test/src/navigation_tree/bloc/navigation_bloc_test.dart [hunk 1]
```diff
@@ -131,6 +136,23 @@ void main() {
       ],
     );
 
+    blocTest<NavigationBloc, NavigationState>(
+      'Emits state with filtered nodes when $LoadNavigationTree event is added '
+      'on an existing query',
+      build: NavigationBloc.new,
+      act: (bloc) => bloc.add(
```
Comment (jenshor) [inline packages/widgetbook_core/test/src/navigation_tree/bloc/navigation_bloc_test.dart:143]: @Roaa94 I matched your style here, but I think this should be named "emits state ..." with a lowercase first letter. 

This is because the test cases are printed like
```
✓ NavigationBloc Emits state with correct nodes when LoadNavigationTree event is added
✓ NavigationBloc Emits state with filtered nodes when LoadNavigationTree event is added on an existing query
```

Just a little FYI 😀
